name: Main-actions

on:
  push
  

jobs:
  make-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: intall
      run:
        make install

    - name: run linter
      run: 
        make lint
